# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  # Build binary dari folder cmd
  cmd = "go build -o ./tmp/main.exe ./cmd"

  # Jalankan hasil binary ini setelah build
  bin = "tmp/main.exe"

  # File dan ekstensi yang dipantau
  include_ext = ["go", "tpl", "tmpl", "html"]

  # Folder yang diabaikan biar Air gak reload gara-gara build
  exclude_dir = ["assets", "tmp", "vendor"]

[log]
  time = true

[dev]
  cmd = "echo 'Running...'"
